version: '3.8'
services:

#==================================================================
  mariadb:

    container_name: ${TRAEFIK}-db

    hostname:       ${SITE}-db

    networks:
      db:
      backend:

    # tested with 10.9.4
    image: docker.io/bitnami/mariadb:latest

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/TZ:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./mariadb/conf/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf
      - ./mariadb/data:/bitnami/mariadb/data
      - ./mariadb/scripts:/bitnami/mariadb/scripts

    restart: ${RESTART}

    environment:
      - TZ=${TIME_ZONE}
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_PORT_NUMBER=${DB_PORT}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_ROOT_USER=${ROOT_USER}
      - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}

    healthcheck:
      test : ['CMD','/bitnami/mariadb/scripts/healthcheck.sh']
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

#==================================================================

  wordpress:

    container_name: ${TRAEFIK}-wp

    hostname:       ${SITE}-wp

    networks:
      web:
      db:

    # tested with 6.1.1i -> wordpress:6
    image: docker.io/bitnami/wordpress:latest

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - ./wordpress/conf/php.ini:/opt/bitnami/php/etc/php.ini
      - ./wordpress/data:/bitnami/wordpress
      - ./wordpress/scripts:/bitnami/scripts

    restart: ${RESTART}

    depends_on:
      - mariadb

    environment:
      - TZ=${TIME_ZONE}

      - WORDPRESS_ENABLE_REVERSE_PROXY=yes

      - WORDPRESS_USERNAME=${WP_USER}
      - WORDPRESS_PASSWORD=${WP_PSWD}
      - WORDPRESS_EMAIL=${WP_EMAIL}
      - WORDPRESS_FIRST_NAM=${WP_FIRST_NAME}
      - WORDPRESS_LAST_NAME${WP_LAST_NAME}

      - WORDPRESS_DATABASE_HOST=${SITE}-db
      - WORDPRESS_DATABASE_PORT_NUMBER=${DB_PORT}
      - WORDPRESS_DATABASE_NAME=${DB_NAME}
      - WORDPRESS_DATABASE_USER=${DB_USER}
      - WORDPRESS_DATABASE_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${TABLE_PREFIX}

      - WORDPRESS_SKIP_BOOTSTRAP=no
      # no --> init and install
      # yes -> already installed

      - WORDPRESS_ENABLE_HTTPS=yes

      - WORDPRESS_HTACCESS_OVERRIDE_NONE=yes

      - WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=yes
      # yes -> /opt/bitnami/wordpress/wordpress-htaccess.conf
      # no --> /opt/bitnami/wordpress/.htaccess

      - WORDPRESS_PLUGINS=`imagemagick-engine`

      - ALLOW_EMPTY_PASSWORD=no

      - PHP_EXPOSE_PHP=no              ##PHP_EXPOSE_PHP: Enables HTTP header with PHP version. No default.
#      - PHP_POST_MAX_SIZE=1024M        ##PHP_POST_MAX_SIZE: Maximum size for PHP POST requests. No default.      #8
#      - PHP_UPLOAD_MAX_FILESIZE=1024M  ##PHP_UPLOAD_MAX_FILESIZE: Maximum file size for PHP uploads. No default. 
#      - PHP_MEMORY_LIMIT=1024M         ##PHP_MEMORY_LIMIT: Memory limit for PHP scripts. Default: 512M

#~ https://developer.wordpress.org/apis/wp-config-php/
      - WORDPRESS_EXTRA_WP_CONFIG_CONTENT=
         define('WP_CACHE', true );

         define('WP_MEMORY_LIMIT', '96M');
         define('WP_MAX_MEMORY_LIMIT', '512M' );

         define('DISALLOW_FILE_EDIT', true);

         define('CONCATENATE_SCRIPTS',true);
         define('COMPRESS_SCRIPTS',true);
         define('COMPRESS_CSS',true);

         define('WP_ENVIRONMENT_TYPE','production');  // production, stating, development, local

         define('EMPTY_TRASH_DAYS', 30);

         define('AUTOSAVE_INTERVAL', 300 ); // Seconds

         define('WP_POST_REVISIONS', 3 );

#~         define( 'WP_CONTENT_URL',  'https://${SITE}/content' );
#~         define( 'WP_INCLUDES_URL', 'https://${SITE}/content/includes' );
#~         define( 'WP_PLUGIN_URL',   'https://${SITE}/content/plugins' );
#~         define( 'WP_UPLOADS_URL',  'https://${SITE}/content/uploads' );
#~
#~         define('FS_CHMOD_DIR',  ( 0755 & ~ umask() ) );
#~         define('FS_CHMOD_FILE', ( 0644 & ~ umask() ) );
#~
#~         define('WP_AUTO_UPDATE_CORE', true);
#~
#~      - WORDPRESS_RESET_DATA_PERMISSIONS=yes

    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.docker.network=traefik4wan
      - traefik.http.routers.${TRAEFIK}.service=${TRAEFIK}
      - traefik.http.routers.${TRAEFIK}.rule=Host(`${SITE}`)
      - traefik.http.routers.${TRAEFIK}.tls=true
      - traefik.http.routers.${TRAEFIK}.tls.certresolver=lets-encrypt
      - traefik.http.routers.${TRAEFIK}.entrypoints=websecure

      - traefik.http.routers.${TRAEFIK}.middlewares=TBA-headers@file,TBA-redirect-htaccess@file,TBA-redirect-license@file

#~LAN~      - traefik.http.middlewares.${TRAEFIK}-whitelist.ipwhitelist.sourcerange=${IP_WHITE_LIST}
#~LAN~      - traefik.http.middlewares.${TRAEFIK}-whitelist.ipwhitelist.ipstrategy.depth=0

      - traefik.http.middlewares.${TRAEFIK}.headers.customrequestheaders.X-Script-Name=production
      - traefik.http.middlewares.${TRAEFIK}.headers.customresponseheaders.X-Custom-Response-Header=true
      - http.middlewares.default-headers.headers.SSLHost=${SITE}

      - traefik.entryPoints.${TRAEFIK}.proxyProtocol.insecure=false #true
      - traefik.entryPoints.${TRAEFIK}.proxyProtocol.trustedIPs=${TRUSTED_IP_LIST}

      - traefik.entryPoints.${TRAEFIK}.forwardedHeaders.insecure=false #true
      - traefik.entryPoints.${TRAEFIK}.forwardedHeaders.trustedIPs=${TRUSTED_IP_LIST}

      - traefik.http.services.${TRAEFIK}.loadbalancer.server.url=http://${SITE}
      - traefik.http.services.${TRAEFIK}.loadbalancer.server.port=8080
      - traefik.http.services.${TRAEFIK}.loadbalancer.passHostHeader=true

    security_opt:
     - no-new-privileges:true

    healthcheck:
      test : ['CMD','/bitnami/scripts/healthcheck.php']
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
 
#==================================================================

networks:
  web:
#~LAN~    name: ${TRAEFIK_4_LAN}
#~WAN~    name: ${TRAEFIK_4_WAN}
    external: true 
  db:
    name: ${SITE}-db
    external: true
  backend:
    name: ${LAN_2_DATABASE}
    external: true
