#!/bin/bash
#
# Created by Quesenbery, D
# ToolbaxAid.com
# Date  10/20/2022
#
# docker-compose.yml
#


version: '3.8'
services:

#==================================================================
services:

# Add the catapp service
  catapp:
     # A Random Cat GIF generator application
     image: mikesir87/cats:1.0

     container_name: ${TRAEFIK}
     hostname:       ${TRAEFIK}

     ports:
       - "5000:5000"

     # We set a label to tell Traefik to assign a hostname to the new service
     labels:
       - "traefik.enable=true"
       - "traefik.docker.network=t${TRAEFIK_4_LAN}"

     # Routers

       - traefik.http.routers.${TRAEFIK}.service=${TRAEFIK}
       - traefik.http.routers.${TRAEFIK}.rule=Host(`${SITE}`)
       - traefik.http.routers.${TRAEFIK}.tls=true
       - traefik.http.routers.${TRAEFIK}.tls.certresolver=${CERT_RESOLVER}
       - traefik.http.routers.${TRAEFIK}.entrypoints=websecure

     # Middle Wares


     # Services

       - traefik.http.services.${TRAEFIK}.loadbalancer.server.url=http://${SITE}
       - traefik.http.services.${TRAEFIK}.loadbalancer.server.port=5000
       - traefik.http.services.${TRAEFIK}.loadbalancer.passHostHeader=true

     restart: $RESTART

     security_opt:
      - no-new-privileges:true

     networks:
      traefik4lan: {}

     healthcheck:
#      test: curl --fail http://localhost || exit 1
       test: wget -S --spider http://localhost:5000/ || exit 1
       interval: 60s
       retries: 5
       start_period: 20s
       timeout: 10s
#==================================================================
networks:
    traefik4lan:
      name: "${TRAEFIK_4_LAN}"
      external: true

